"""rename recorrente to is_recurrent

Revision ID: 78f73cc0f073
Revises: 1e82dd7afa29
Create Date: 2026-04-25 15:15:05.419978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f73cc0f073'
down_revision: Union[str, None] = '1e82dd7afa29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('is_recurrent', sa.Boolean(), nullable=True))
    op.drop_column('incomes', 'recorrente')
    op.drop_column('incomes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('incomes', sa.Column('recorrente', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('incomes', 'is_recurrent')
    # ### end Alembic commands ###