"""SM-11 cria tabela incomes

Revision ID: 851fc38d9575
Revises: 7894f3e66eb2
Create Date: 2026-04-25 14:50:44.365711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851fc38d9575'
down_revision: Union[str, None] = '7894f3e66eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###