"""add created_at to incomes

Revision ID: d0f7ba50f7ee
Revises: 78f73cc0f073
Create Date: 2026-04-25 15:18:30.852361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f7ba50f7ee'
down_revision: Union[str, None] = '78f73cc0f073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'created_at')
    # ### end Alembic commands ###